# Generated by Django 4.2.5 on 2023-09-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="email",
            field=models.EmailField(default="test@gmail.com", max_length=100),
        ),
    ]
